---
# Global variables for all hosts
# These variables apply to all nodes in the inventory

# Common role configuration
common_timezone: "Asia/Tokyo"
common_admin_user: "homelab"
common_ssh_port: 22
common_ssh_password_auth: false
common_ssh_root_login: false

# System optimization (minimal for k3s)
common_update_cache: true
common_upgrade_packages: false

# Firewall configuration
common_ufw_enabled: true
common_ufw_rules:
  - { rule: "allow", port: "{{ common_ssh_port }}", proto: "tcp" }
  - { rule: "allow", port: "6443", proto: "tcp" }  # k3s API server
  - { rule: "allow", port: "10250", proto: "tcp" } # kubelet
  - { rule: "allow", port: "2379:2380", proto: "tcp" } # etcd

# k3s common configuration
k3s_version: "v1.33.1+k3s1"
k3s_disable_swap: true

# k3s network configuration - TO BE CONFIGURED
# TODO: Configure these values before deployment
k3s_cluster_cidr: "{{ K3S_CLUSTER_CIDR | default('10.42.0.0/16') }}"  # TODO: Set actual cluster CIDR
k3s_service_cidr: "{{ K3S_SERVICE_CIDR | default('10.43.0.0/16') }}"  # TODO: Set actual service CIDR
k3s_cluster_dns: "{{ K3S_CLUSTER_DNS | default('10.43.0.10') }}"      # TODO: Set actual cluster DNS IP

# NFS client configuration
nfs_mount_base: "/mnt/nfs"
nfs_mount_options: "rw,sync,hard,intr,rsize=8192,wsize=8192,timeo=14"

# Logging configuration
ansible_log_path: "./ansible.log"