# SOPS の復号が効いているかを確かめるための一時的なもの。確認後に削除する。
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-test
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/default/sops-test/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
