apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: network
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:aADew3GM36etxOrj3YhfoImgvnUKFXBPTnLzLxC8wJTvbnYi4krMC06SeDJTR1ZlauLCQM38kMvuM68/sE52PpiFlfapKN0SsINwx1ARfe+1KSU1e7q69MzEhQKwHxRnPcf6Amh6kKIU/xRhPq4FTm0Png+DigYAWjnfcL/u5E0iXEVIZU5G+59J8ZoxLzej1y1IAI7yuRlxVeNyZWRLteLg3jYakUGBIDg+b8XMkg==,iv:njafnInPlKd/s4oAMdOu4sBFjK2h9xaekzcUB4CA2gQ=,tag:OGfmxtDNUCqjLMPmDjC6oQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R3dqK2Vqb21tMU9CZWNp
            cXMxSmxvL0c5RTZoUjRtR3dtTkJnWjZIWlN3Cjlha01rUEt6ZWtDQ0N3L21DcUpm
            ZHVQM2VTYnpPWGRITVpOU1Y4TTlVMlEKLS0tIHhNaHMzbGxCWXpvTmFxY0JWNE9l
            eko1dnUrWUlrdXJoZWFhOEUralRic3MK6Zdhxf+Ge5J6+Q4HDsL8nMb00JJZ0xlB
            u+h/CbPFd9GfsqeQjgQQ51+VxByswzqsKGRRj6WgAXsX8bOjMxaXgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k03mxpgxqe2kn2m4njawxjjd9mt70t90q6qzvrwn4eeqxpk6ad5sy9pm0j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T12:54:04Z"
    mac: ENC[AES256_GCM,data:ocqp67sS2riWGs0QtR43KDx3fy9huBLjK2SK7LVqayfZFb8RKbJxPxWYVwBjG0BRV6BdtSRrINU3wEmDMENvLFsOn3yVvPm/WwsA5OokVjEpil/JRfAWksbBgfE1Y25Boo/yCrEc21hl7s7VA03x7ZE+SORCBCCT+IAd9pTMYW0=,iv:rTadThdXC0gwezj8l+2y6bBP83Vb7gSI4SCzyApBbgU=,tag:1MxCjfXkZHfvRnn87jRLsA==,type:str]
    version: 3.13.3
