apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: network
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:aADew3GM36etxOrj3YhfoImgvnUKFXBPTnLzLxC8wJTvbnYi4krMC06SeDJTR1ZlauLCQM38kMvuM68/sE52PpiFlfapKN0SsINwx1ARfe+1KSU1e7q69MzEhQKwHxRnPcf6Amh6kKIU/xRhPq4FTm0Png+DigYAWjnfcL/u5E0iXEVIZU5G+59J8ZoxLzej1y1IAI7yuRlxVeNyZWRLteLg3jYakUGBIDg+b8XMkg==,iv:njafnInPlKd/s4oAMdOu4sBFjK2h9xaekzcUB4CA2gQ=,tag:OGfmxtDNUCqjLMPmDjC6oQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM0tLMEZJay8yc00vd0pm
            MHJ1Yzl5Ui9JTnZPYzBacFFpMldBZk1VdUFJCkpqdkthTFNrWG94WTVHaHYwNUhi
            TEtuQzcwcDhRWWl5THUxWmlDVEJCMVEKLS0tIGVGMUZJRi9ZUGY3L09CUGxLV0R6
            NWtPaTlIbEpSdk5jcE5PRVRvczF3UjgKZY0iD1gkYSL9QR0N3N3cx9OqlzlaYZEP
            Heh17IOFufHDqqgobBm/YYcrYZN6m5lBbtClGvvXhOXAi+YVOGPcCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k03mxpgxqe2kn2m4njawxjjd9mt70t90q6qzvrwn4eeqxpk6ad5sy9pm0j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTDd0OTRiOWhoSHVPdHNx
            UlozK1QxWkpBaS9nWGYwNXVsWklqR2RraDJRCkZXVWZxZ25qOEhiUk5Fb1I2R29n
            OTRPTWtINHZDSTRzZHdQM244b2hRZ00KLS0tIGFtM2VsZHRyWCtJQzc2QW8wd0F0
            MW9USlY4OWVkRC9INXNDR3hRZGxGNEkK2YPlcpE3DIo1kngCaW9RkE1dz228KopV
            yMijf5vNXgI9NQHEw28c15sY4MzBimx2fWmO/IHmEo9vMBNnTsETxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13n75cytyd93xp44meu7arr3rn0n9m2pwps9h4vmd9jzx9cxhhuuqvkyzg4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T12:54:04Z"
    mac: ENC[AES256_GCM,data:ocqp67sS2riWGs0QtR43KDx3fy9huBLjK2SK7LVqayfZFb8RKbJxPxWYVwBjG0BRV6BdtSRrINU3wEmDMENvLFsOn3yVvPm/WwsA5OokVjEpil/JRfAWksbBgfE1Y25Boo/yCrEc21hl7s7VA03x7ZE+SORCBCCT+IAd9pTMYW0=,iv:rTadThdXC0gwezj8l+2y6bBP83Vb7gSI4SCzyApBbgU=,tag:1MxCjfXkZHfvRnn87jRLsA==,type:str]
    version: 3.13.3
