---
- name: Install systemd-timesyncd
  apt:
    name: systemd-timesyncd
    state: present
  tags: ntp

- name: Configure timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    backup: true
  notify: restart systemd-timesyncd
  tags: ntp

- name: Enable and start systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
  tags: ntp

- name: Disable other NTP services if present
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - ntp
    - chrony
  failed_when: false
  tags: ntp
