---
- name: Add NVIDIA Container Toolkit repository GPG key
  apt_key:
    url: "https://nvidia.github.io/libnvidia-container/gpgkey"
    state: present
  tags: container

- name: Add NVIDIA Container Toolkit repository
  apt_repository:
    repo: "deb https://nvidia.github.io/libnvidia-container/stable/ubuntu{{ ansible_distribution_version }}/amd64 /"
    state: present
    filename: nvidia-container-toolkit
  tags: container

- name: Update apt cache for container toolkit
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: container

- name: Install NVIDIA Container Toolkit
  apt:
    name:
      - nvidia-container-toolkit
      - nvidia-container-runtime
    state: present
  when: nvidia_container_toolkit_enable
  tags: container

- name: Configure containerd for NVIDIA runtime
  template:
    src: containerd-nvidia.toml.j2
    dest: /etc/containerd/conf.d/nvidia.toml
    mode: '0644'
  notify: restart containerd
  when: nvidia_container_runtime_enable
  tags: container

- name: Generate NVIDIA container runtime configuration
  command: nvidia-ctk runtime configure --runtime=containerd
  when: nvidia_container_runtime_enable
  notify: restart containerd
  tags: container