apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:3hh7TqMt6vc5uweCvj0u1j6RjKlrmsGVd8Ie2gecw8RdqjsfMS1Oz4+VHLAYynvElGgDgUQ=,iv:9/SxLJZqkCbwQ71Zk9FtwwBTA7Mc0xuOSEfa43ePN1Q=,tag:32kCgxOKmePJT1x6EVbZOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTDBDazNtanIrMUtDcXo4
            emtZTktZdWxqbGFsVk5JL054Y2VGY1hQQzI4Ci9ONHVyekwwWk1uQkNVck9QTHhh
            eHBVeDY5RTNsaFpPYm04bm5lYm1ncTAKLS0tIFJvZzVzOTA4NUhwY3pQYyszT1RU
            VGhKQ1FlUXlHSWVnd2ZHWjBQU1NIUE0KsZnZAWcyyP6ZAqHfwfE8eV6eB9UOKLOj
            uTeJxwFKSCkCvyex9MswHe/YG/VYgDz5xfsSI6mGm8Sn7Y3V+Z5l8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k03mxpgxqe2kn2m4njawxjjd9mt70t90q6qzvrwn4eeqxpk6ad5sy9pm0j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVHBjOHZxMTVNSjA1YXFo
            QndRM0d1TWNJUnlDaUZjM2Q4RTJDdVl1Y2tBCkxqb09ZWUQ4MC9uTDRWVUd3L1d2
            VG9IN1J0WHFQNE41M092bU9wTHBDUGcKLS0tIFF2aWRoNXRielNyeThFcUpNOUt0
            UmNTK05vUUtJZWQxWm5ra2prNkVoVTAK1oSGU8+0TwWAbaS8QhZOPdOTXWbakGEC
            wDjECKtcM7qBaayuG5ku9UJSh3lkC4mc9nAeFuundDRWkVXlIfvqpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13n75cytyd93xp44meu7arr3rn0n9m2pwps9h4vmd9jzx9cxhhuuqvkyzg4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T12:45:33Z"
    mac: ENC[AES256_GCM,data:FeDio7lhQEf69k1k1h2XeYPGFVkdj+Lj5/nOcjX1lV7pFSTrNYmI0H/GV0qmOtY6tvqI22kcidR93oggCeLv+XwMMlk5/fRCnh/cy3X+KKZmzMoeFZAxbz+VhVSzMOKwYSbePtRf6y+3fA+3v4dza3Ut7S6XcxhDci2zG5ALp2M=,iv:4fKWHv1m+XS8wrJ/vSIevc9rsFrtbsxWHY+i/h3WxDk=,tag:wkx4j/uZdZMwwWqhQbSp7Q==,type:str]
    version: 3.13.3
