apiVersion: v1
kind: Secret
metadata:
    name: sops-test
    namespace: default
stringData:
    message: ENC[AES256_GCM,data:ih3ZFcTmxd7y5p69EWeNB0Pe7cDG,iv:0FgcxO84thFHyqAwY6nABzqzcBlTJ9OV0e7T/IhWnfQ=,tag:q/xGEHVWUrqQ+NYm0DF5JA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NTJKWko4T1I1dzRPRDVJ
            TkpLRjJibDhObXhqTlh6Ukh1SWh0NnBsbEZBCkpBUUp5Ni8yL2kzT2JGeE0wdmNC
            R3J4V0FVYzJaNEN5NWlOQU1NaGI0MEkKLS0tIE1KVXUyVXRwZTc1bE95VDZ6VkhV
            VGFZY0hiaFFJMUt3Ly9xK1p5NHRvZTQKjPCx3iWhOzTUn5abw8bLj5LznHfEwzin
            tQslHixCHW5wQXXrG7+oi8J7km0+/JPRJvjk6XhyUewJPtYNZyWtTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k03mxpgxqe2kn2m4njawxjjd9mt70t90q6qzvrwn4eeqxpk6ad5sy9pm0j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T05:40:45Z"
    mac: ENC[AES256_GCM,data:Ne1p3SDWbS+z+Ma9+zxfogZDaJSaN1hj9gtBdchif6NX4bpF8+iatfNOF6XKGHbR1ZphuEtzAVUeoD2Sqk2gW0PlhufGBWvWyckNyOHEpk3T4zMWwa79WIJpB3j4X51sNsCmtSFb4JEPA7jzR9jRLRpDtLh/58vAjuUFaM+c7mg=,iv:pSbilkVF86ZPXH3uT5cn+nrx7uM8CTgJLEr/ee6TbFk=,tag:3VII9rfNtkOBUd9maqcQow==,type:str]
    version: 3.13.3
