---
- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ k3s_required_kernel_modules }}"
  tags: kernel

- name: Ensure kernel modules are loaded at boot
  lineinfile:
    path: /etc/modules-load.d/k3s.conf
    line: "{{ item }}"
    create: true
  loop: "{{ k3s_required_kernel_modules }}"
  tags: kernel

- name: Verify kernel modules are loaded
  command: lsmod
  register: lsmod_output
  changed_when: false
  tags: kernel

- name: Check if required modules are loaded
  assert:
    that:
      - item in lsmod_output.stdout
    fail_msg: "Required kernel module {{ item }} is not loaded"
    quiet: true
  loop: "{{ k3s_required_kernel_modules }}"
  tags: kernel