---
galaxy_info:
  author: homelab-admin
  description: Common k3s preparation for all nodes
  company: homelab
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies:
  - role: common
