---
- name: Check if k3s binary exists and get version
  stat:
    path: "{{ k3s_bin_dir }}/k3s"
  register: k3s_binary_stat
  tags: download

- name: Get current k3s version if installed
  command: "{{ k3s_bin_dir }}/k3s --version"
  register: k3s_current_version
  when: k3s_binary_stat.stat.exists
  changed_when: false
  failed_when: false
  tags: download

- name: Set k3s version facts
  set_fact:
    k3s_needs_install: >-
      {{
        not k3s_binary_stat.stat.exists or
        (k3s_current_version.stdout is defined and
         k3s_version not in k3s_current_version.stdout)
      }}
  tags: download

- name: Download k3s binary
  get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: "{{ k3s_bin_dir }}/k3s"
    mode: '0755'
    owner: root
    group: root
  when: k3s_needs_install
  tags: download

- name: Download k3s install script
  get_url:
    url: "https://get.k3s.io"
    dest: "/tmp/k3s-install.sh"
    mode: '0755'
  when: k3s_needs_install
  tags: download
