---
# Playbook for preparing all nodes with basic OS configuration
# This should be run first before any k3s installation

- name: Prepare all nodes with basic OS configuration
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Display target nodes
      debug:
        msg: "Preparing node: {{ inventory_hostname }} ({{ ansible_default_ipv4.address }})"
      tags: always

    - name: Wait for nodes to be ready
      wait_for_connection:
        timeout: 300
      tags: always

  roles:
    - role: common
      tags: [common, os]

  post_tasks:
    - name: Display preparation completion
      debug:
        msg: "Node {{ inventory_hostname }} preparation completed successfully"
      tags: always

    - name: Reboot nodes if required
      reboot:
        reboot_timeout: 600
        connect_timeout: 20
        test_command: uptime
      when: reboot_required | default(false)
      tags: reboot

- name: Prepare k3s prerequisites on all nodes
  hosts: k3s_cluster
  become: true
  gather_facts: true

  roles:
    - role: k3s_common
      tags: [k3s_common, prerequisites]

  post_tasks:
    - name: Display k3s prerequisites completion
      debug:
        msg: "k3s prerequisites installed on {{ inventory_hostname }}"
      tags: always

- name: Prepare NFS client on worker nodes
  hosts: k3s_worker
  become: true
  gather_facts: true

  roles:
    - role: nfs_client
      tags: [nfs_client, storage]
      when: nfs_client_server_ip is defined and nfs_client_server_ip != ""

  post_tasks:
    - name: Display NFS client setup completion
      debug:
        msg: "NFS client configured on {{ inventory_hostname }}"
      when: nfs_client_server_ip is defined and nfs_client_server_ip != ""
      tags: always

- name: Prepare NVIDIA drivers on worker nodes with GPU
  hosts: k3s_worker
  become: true
  gather_facts: true

  roles:
    - role: nvidia_driver
      tags: [nvidia_driver, gpu]
      when: "'gpu' in group_names"

  post_tasks:
    - name: Display NVIDIA driver setup completion
      debug:
        msg: "NVIDIA drivers installed on {{ inventory_hostname }}"
      when: "'gpu' in group_names"
      tags: always

- name: Prepare Docker on designated nodes (optional)
  hosts: docker_hosts
  become: true
  gather_facts: true

  roles:
    - role: docker
      tags: [docker, containers]
      when: docker_install | default(false)

  post_tasks:
    - name: Display Docker setup completion
      debug:
        msg: "Docker installed on {{ inventory_hostname }}"
      when: docker_install | default(false)
      tags: always
