apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IXoed4WxdU8TUwUu,iv:3t3C0b8/pF0AO46R+LTYTyf/VTSpc6N07RYC3HnPgLk=,tag:GugIHt5q/ywa2m9lLel03A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iO9blzN1Fv4vug2TY7eE26RjcTDKkx6awrJo9rH1oeCJW+XN,iv:it3HtRmYg4RRic1b3Z8o8cG46+a3XlYlsGZ5yVtCiI4=,tag:64fno9JkWXNMNSIO7GdkVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaUVUdjEwaVZ3RWd0UG5t
            ZzhDalVDczQ4QnpTVUpRTXFwMHpTV2E3YzN3Cld3UmIyY3lVYmZzcllTTUlJZi9v
            Z1A3R3NLSURxdkZ6aGJ2R3RMcDlaeGsKLS0tIFJra2pXZTltWDFTcUtlaTkwKy93
            RDE5SWluRno0SnYxTWNuamYvNmNrcGcK1lSv7WAkLvbqhuynIHA4JDEmKGAYOUcw
            XmWuvIxKUhSbmuWR5AcQMK0N8C8Ed5mO/f3UNVzy2yiT83qsBoXDdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k03mxpgxqe2kn2m4njawxjjd9mt70t90q6qzvrwn4eeqxpk6ad5sy9pm0j
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MzQvYXpOTFJ4K1ovejNy
            d3p1VjVER3lMRElVYk01M1lkaVpwUWhXdkVNCmtHVm5ubGI4UHo1OXBnRUcxMFU3
            SzBPUzRlRFVLVFVBVUlEeThHZG5YV2cKLS0tIGowbFF5WURPT3VzWVNiRkszZDFS
            TVBZQ1JmL3FzM3ZEb0J5Q29hWHQxZDgK5TRcLO/+5gpq2CY7X7wd3vXbgYAcN8TW
            CVWDqXLGtNTRYRM3+HwpjzEqnLDXancW1HqEBgjGXXDN7Vn7DyLv1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13n75cytyd93xp44meu7arr3rn0n9m2pwps9h4vmd9jzx9cxhhuuqvkyzg4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T12:53:26Z"
    mac: ENC[AES256_GCM,data:6I4JQy5xJJn1ztR5u/l8BV/j0hlvOj7H9DdmlpSe8kmAmjnh1mR7QFresf78NFWfv+3PRvZZpNmlFUS8bQgAxtRwt0eZERwks0aguSt/e4UMhlyR5fji35C6x/j1YjyIy6oM3dCY0N7c0Z/KRzjbFjddnStn9iipjNAgktIL+a8=,iv:5xJYp2QLrvEee8IdpIH7wAoM4hx5ygpY9YvGJ46/tZA=,tag:0dfRs0hOU4uD96TqRGAclA==,type:str]
    version: 3.13.3
