apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IXoed4WxdU8TUwUu,iv:3t3C0b8/pF0AO46R+LTYTyf/VTSpc6N07RYC3HnPgLk=,tag:GugIHt5q/ywa2m9lLel03A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iO9blzN1Fv4vug2TY7eE26RjcTDKkx6awrJo9rH1oeCJW+XN,iv:it3HtRmYg4RRic1b3Z8o8cG46+a3XlYlsGZ5yVtCiI4=,tag:64fno9JkWXNMNSIO7GdkVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmR1ZMc0d1T2JtMWVkYzRr
            WnNJM1hhazRMa3kvQ1NxaUJmRXFGaE5wSldNCitBS0EwemJib1FQL3BZTGdyVHlJ
            WHlRZEMvNVlFV1NNZGtUMElWZHlzSXMKLS0tIGJYdHRVWm1YQ0lPaS8zVjZUaCsy
            Q3BZUUtDVnZNdzc2MHk2eFFNL0hLRTAKDWPy05k8iLOFJcGlI44iJkou2yunXWmO
            Cdtl0BUINlhdqa9y8a4Jg+jNzOSrRCKyWmnyTYiGZjSfJijblY1GAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k03mxpgxqe2kn2m4njawxjjd9mt70t90q6qzvrwn4eeqxpk6ad5sy9pm0j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T12:53:26Z"
    mac: ENC[AES256_GCM,data:6I4JQy5xJJn1ztR5u/l8BV/j0hlvOj7H9DdmlpSe8kmAmjnh1mR7QFresf78NFWfv+3PRvZZpNmlFUS8bQgAxtRwt0eZERwks0aguSt/e4UMhlyR5fji35C6x/j1YjyIy6oM3dCY0N7c0Z/KRzjbFjddnStn9iipjNAgktIL+a8=,iv:5xJYp2QLrvEee8IdpIH7wAoM4hx5ygpY9YvGJ46/tZA=,tag:0dfRs0hOU4uD96TqRGAclA==,type:str]
    version: 3.13.3
