---
galaxy_info:
  author: homelab-admin
  description: Docker installation and configuration for application builds
  company: homelab
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
