---
- name: Check if Docker Compose plugin is installed
  command: docker compose version
  register: docker_compose_check
  changed_when: false
  failed_when: false
  tags: compose

- name: Display Docker Compose plugin status
  debug:
    msg: >
      {% if docker_compose_check.rc == 0 %}
      Docker Compose plugin is already installed: {{ docker_compose_check.stdout }}
      {% else %}
      Docker Compose plugin is not available
      {% endif %}
  tags: compose

- name: Install Docker Compose standalone (fallback)
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    owner: root
    group: root
  when: docker_compose_check.rc != 0
  tags: compose

- name: Create docker-compose symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
  when: docker_compose_check.rc != 0
  tags: compose

- name: Verify Docker Compose installation
  command: docker compose version
  register: docker_compose_verify
  changed_when: false
  tags: compose

- name: Display Docker Compose version
  debug:
    msg: "{{ docker_compose_verify.stdout }}"
  tags: compose