---
- name: Remove old Docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags: install

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  notify: restart docker
  tags: install

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  tags: install

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: "{{ docker_service_enabled }}"
    state: "{{ docker_service_state }}"
    daemon_reload: true
  tags: install