---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/cert-manager/ks.yaml
  - longhorn-system/longhorn/ks.yaml
  - network/gateway/ks.yaml
  - network/cloudflared/ks.yaml
  - network/external-dns/ks.yaml
