---
# Ansible inventory for k3s homelab cluster
# Update IP addresses and hostnames to match your actual environment

all:
  vars:
    # Global variables - CONFIGURE THESE VALUES
    ansible_user: homelab
    ansible_ssh_private_key_file: ~/.ssh/homelab_key  # TODO: Set actual SSH key path
    ansible_become: true
    ansible_become_method: sudo
    
    # Network configuration - TO BE CONFIGURED
    # Update these with your actual network configuration
    control_plane_cidr: "{{ CONTROL_PLANE_CIDR | default('192.168.1.10/24,192.168.1.11/24,192.168.1.12/24') }}"  # TODO: Set actual CIDR
    control_plane_vip: "{{ CONTROL_PLANE_VIP | default('192.168.1.10') }}"  # TODO: Set actual VIP
    worker_nodes_cidr: "{{ WORKER_NODES_CIDR | default('192.168.1.20/24,192.168.1.21/24') }}"  # TODO: Set actual CIDR
    
    # NFS configuration - TO BE CONFIGURED
    nfs_server_ip: "{{ NFS_SERVER_IP | default('') }}"  # TODO: Set NFS server IP
    nfs_export_path: "{{ NFS_EXPORT_PATH | default('/nfs/k3s') }}"  # TODO: Set NFS export path
    
    # k3s configuration - TO BE CONFIGURED
    k3s_token: "{{ K3S_TOKEN | default('your-secure-k3s-token-here') }}"  # TODO: Generate secure token
    k3s_control_plane_endpoint: "{{ control_plane_vip }}"
    k3s_server_url: "https://{{ k3s_control_plane_endpoint }}:6443"

  children:
    # k3s cluster nodes
    k3s_cluster:
      children:
        k3s_control_plane:
          hosts:
            # Control plane nodes (Minisforum S100)
            cp-01:
              ansible_host: 192.168.1.10  # TODO: Set actual IP
              ansible_hostname: cp-01
            cp-02:
              ansible_host: 192.168.1.11  # TODO: Set actual IP
              ansible_hostname: cp-02
            cp-03:
              ansible_host: 192.168.1.12  # TODO: Set actual IP
              ansible_hostname: cp-03
        
        k3s_worker:
          hosts:
            # Worker nodes (Minisforum MS-02)
            worker-01:
              ansible_host: 192.168.1.20  # TODO: Set actual IP
              ansible_hostname: worker-01
            worker-02:
              ansible_host: 192.168.1.21  # TODO: Set actual IP
              ansible_hostname: worker-02
    
    # Nodes with GPU capability
    gpu:
      hosts:
        worker-01:
        worker-02:
    
    # Nodes for Docker installation (optional)
    docker_hosts:
      hosts:
        # Add nodes here if Docker CLI is needed for builds
        # worker-01:
        # worker-02:
      vars:
        docker_install: false  # Set to true to enable Docker installation

# Hardware-specific groupings
minisforum_s100:
  hosts:
    cp-01:
    cp-02:
    cp-03:
  vars:
    # Minisforum S100 specific configurations
    hardware_type: "minisforum_s100"
    cpu_type: "intel_n100"
    memory_gb: 8
    storage_gb: 128

minisforum_ms02:
  hosts:
    worker-01:
    worker-02:
  vars:
    # Minisforum MS-02 specific configurations
    hardware_type: "minisforum_ms02"
    cpu_type: "amd_ryzen_9_7945hx"
    gpu_type: "nvidia_rtx_a400"
    memory_gb: 32
    storage_gb: 512