---
galaxy_info:
  author: homelab-admin
  description: NFS client configuration for worker nodes
  company: homelab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 24.04

dependencies: []